# Generated by Django 4.1.9 on 2024-01-15 10:11

import wagtail.blocks
import wagtail.fields
import wagtail.snippets.blocks
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("cms", "0004_homepage_video_blocks"),
    ]

    operations = [
        migrations.AlterField(
            model_name="homepage",
            name="video_blocks",
            field=wagtail.fields.StreamField(
                [
                    (
                        "video",
                        wagtail.blocks.StructBlock(
                            [
                                (
                                    "video",
                                    wagtail.snippets.blocks.SnippetChooserBlock(
                                        target_model="wideo.Video"
                                    ),
                                ),
                                (
                                    "autoplay",
                                    wagtail.blocks.BooleanBlock(required=False),
                                ),
                                (
                                    "controls",
                                    wagtail.blocks.BooleanBlock(required=False),
                                ),
                            ]
                        ),
                    )
                ],
                blank=True,
                null=True,
                use_json_field=True,
            ),
        ),
    ]
