# Generated by Django 4.1.9 on 2023-05-08 15:46

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import watch_this.utils.storage


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="VideoFile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "file",
                    models.FileField(
                        help_text="The video file",
                        upload_to=watch_this.utils.storage.upload_to,
                        verbose_name="File",
                    ),
                ),
                (
                    "file_name",
                    models.CharField(
                        help_text="Original name of the file",
                        max_length=1000,
                        verbose_name="File name",
                    ),
                ),
                (
                    "file_size",
                    models.IntegerField(
                        help_text="Size of the file in bytes", verbose_name="File size"
                    ),
                ),
                (
                    "date_create",
                    models.DateTimeField(
                        auto_now_add=True,
                        help_text="Date of creation",
                        verbose_name="Date create",
                    ),
                ),
                (
                    "owner",
                    models.ForeignKey(
                        blank=True,
                        help_text="The owner of the video (if any)",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Owner",
                    ),
                ),
            ],
        ),
    ]
