# Generated by Django 4.1.9 on 2023-05-08 15:46

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("watch_this_upload", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Video",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("processing", "Processing"),
                            ("success", "Success"),
                            ("failed", "Failed"),
                        ],
                        default="pending",
                        help_text="The status of the video processing (pending means nothing happens on this video yet, processing means the task is running, success means a render is available and failed means the task failed)",
                        max_length=10,
                        verbose_name="Status",
                    ),
                ),
                (
                    "date_create",
                    models.DateTimeField(
                        auto_now_add=True,
                        help_text="Date of creation of the video",
                        verbose_name="Date of creation",
                    ),
                ),
                (
                    "file",
                    models.ForeignKey(
                        help_text="Reference to the video file",
                        on_delete=django.db.models.deletion.CASCADE,
                        to="watch_this_upload.videofile",
                        verbose_name="File",
                    ),
                ),
                (
                    "owner",
                    models.ForeignKey(
                        blank=True,
                        help_text="The owner of the video (if any)",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Owner",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Render",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "date_create",
                    models.DateTimeField(
                        auto_now_add=True,
                        help_text="Date of creation of the render",
                        verbose_name="Date of creation",
                    ),
                ),
                (
                    "thumbnails",
                    models.JSONField(
                        default=dict,
                        help_text="Thumbnails of the video",
                        verbose_name="Thumbnails",
                    ),
                ),
                (
                    "videos",
                    models.JSONField(
                        default=dict,
                        help_text="Web-rendered videos",
                        verbose_name="Videos",
                    ),
                ),
                (
                    "duration_seconds",
                    models.FloatField(
                        help_text="Duration of the video in seconds",
                        verbose_name="Duration in seconds",
                    ),
                ),
                (
                    "original_width",
                    models.IntegerField(
                        help_text="Width of the original video in pixels",
                        verbose_name="Original width",
                    ),
                ),
                (
                    "original_height",
                    models.IntegerField(
                        help_text="Height of the original video in pixels",
                        verbose_name="Original height",
                    ),
                ),
                (
                    "original_fps",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="FPS of the original video",
                        max_digits=5,
                        verbose_name="Original FPS",
                    ),
                ),
                (
                    "original_frame_count",
                    models.IntegerField(
                        help_text="Number of frames in the original video",
                        verbose_name="Original frame count",
                    ),
                ),
                (
                    "video",
                    models.OneToOneField(
                        help_text="The video that was rendered",
                        on_delete=django.db.models.deletion.CASCADE,
                        to="watch_this_base.video",
                        verbose_name="Video",
                    ),
                ),
            ],
        ),
    ]
